Repository atlp-rwanda/e-comm-team-brogrammers-bn, pull requests merged in 2023-03, with the labels that each got.

#1 #184581316 Set up an empty Node.js - express application.
  .DS_Store
  .babelrc
  .env.example
  jest.config.js
  package-lock.json
  package.json
  src/app.js
  src/controllers/index.js
  src/helpers/helpers
  src/middlewares/middleware
  src/routes/index.js
  src/services/index.js
  src/validations/validations
  tests/index.test.js
Labels: enhancement

#10 remove DS_Strore file
  .DS_Store
  .gitignore
Labels: bug, ready for review

#16 #184581324 Setting up Swagger Documentation
  .env.example
  package-lock.json
  package.json
  src/app.js
  src/configs/swagger.js
  src/database/config/config.js
  src/docs/home.js
Labels: documentation, enhancement, ready for review

#7 #184581319 Setup eslint
  .eslintrc.json
  .github/workflows/eslint.yml
  .hound.yml
  jest.config.js
  package-lock.json
  package.json
  src/app.js
  src/configs/swagger.js
  src/controllers/index.js
  src/database/config/config.js
  src/database/migrations/20230302083923-create-user.js
  src/database/migrations/20230302085457-create-post.js
  src/database/models/index.js
  src/database/models/post.js
  src/database/models/user.js
  src/database/seeders/20230302090115-User.js
  src/database/seeders/20230302090142-Post.js
  src/docs/home.js
  src/routes/index.js
  src/server.js
  src/services/index.js
  tests/index.test.js
Labels: ready for review

#12 #184581326 Setup docker-compose
  .dockerignore
  .env.example
  Dockerfile
  docker-compose.yml
  src/.prettierrc
Labels: ready for review

#2 #184581318 Setup Unit Testing
  jest.config.js
  package-lock.json
  package.json
  tests/index.test.js
Labels: ready for review

#18 #184581321 Integrate coveralls code coverage service
  .coveralls.yml
  .env.example
  .github/pull_request_template.md
  README.md
  package-lock.json
  package.json
Labels: ready for review

#20 ch(deploy base application on render): implement deployment
  .env.example
Labels: documentation, ready for review

#21 #184629384 user signup with validations
  .circleci/config.yml
  .env.example
  README.md
  package-lock.json
  package.json
  src/controllers/users.controllers.js
  src/database/config/config.js
  src/database/migrations/20230302083923-create-user.js
  src/database/migrations/20230302085457-create-post.js
  src/database/migrations/20230308210129-create-users.js
  src/database/models/index.js
  src/database/models/post.js
  src/database/models/user.js
  src/database/models/users.js
  src/database/seeders/20230302090115-User.js
  src/database/seeders/20230302090142-Post.js
  src/database/seeders/20230309104901-users.js
  src/docs/users.js
  src/middlewares/checkUserExist.js
  src/middlewares/middleware
  src/middlewares/signupValidate.js
  src/routes/index.js
  src/routes/users.js
  src/server.js
  src/services/user.services.js
  src/validations/signup.validation.js
  src/validations/validations
  tests/users.test.js
Labels: documentation, enhancement, ready for review

#26 #184664900 add uuid as userid
  package-lock.json
  package.json
  src/database/migrations/20230308210129-create-users.js
  src/database/models/users.js
  src/database/seeders/20230309104901-users.js
  tests/users.test.js
Labels: enhancement, ready for review

#27 #184581329 Receiving email verification link upon…
  .dockerignore
  .env.example
  .prettierrc
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  src/controllers/users.controllers.js
  src/database/config/config.js
  src/database/migrations/20230309212534-add-verified-to-users.js
  src/database/migrations/20230310062139-email_token_to_users.js
  src/database/migrations/20230310065311-modify_users_add_new_fields.js
  src/database/models/users.js
  src/docs/users.js
  src/helpers/emailConfig.js
  src/helpers/helpers
  src/helpers/jwt.js
  src/helpers/mail.js
  src/helpers/mailTemplate.js
  src/middlewares/loginValidate.js
  src/routes/users.js
  src/services/user.services.js
  src/validations/login.validation.js
  src/validations/signup.validation.js
  tests/email.test.js
  tests/login.test.js
  tests/users.test.js
Labels: enhancement, ready for review

#24 #184581333 ft(authorization):Protecting routes
  package-lock.json
  src/middlewares/verifyToken.js
  src/routes/auth.routes.js
Labels: ready for review

#28 #184686439 BUG(Fix Readme)
  README.md
Labels: enhancement, ready for review

#31 #184581336 Profile Page Setting (GET and PATCH)
  README.md
  src/controllers/users.controllers.js
  src/database/seeders/20230309104901-users.js
  src/docs/users.js
  src/middlewares/profileValidate.js
  src/middlewares/verifyToken.js
  src/routes/users.js
  src/services/user.services.js
  src/validations/profile.validate.js
  tests/users.test.js
Labels: documentation, enhancement, ready for review

#33 #184664608 Admin can create another admin
  README.md
  src/controllers/users.controllers.js
  src/database/seeders/20230309104901-users.js
  src/docs/users.js
  src/middlewares/Checkrole.js
  src/routes/users.js
  tests/users.test.js
Labels: ready for review

#36 #184699564 verify email after update profile
  src/controllers/users.controllers.js
  src/routes/users.js
  src/services/user.services.js
  tests/users.test.js
Labels: ready for review

#35 #184581340 User can change password
  README.md
  src/controllers/users.controllers.js
  src/docs/users.js
  src/routes/users.js
  tests/users.test.js
Labels: enhancement, ready for review

#34 #184581335 Add Multi-Factor Authentication(MFA)
  .env.example
  README.md
  package.json
  src/controllers/users.controllers.js
  src/database/migrations/20230314092003-add_mfa_code_to_users_table.js
  src/database/migrations/20230314123346-add_mfa_enabled_to_users_table.js
  src/database/models/users.js
  src/docs/users.js
  src/helpers/mailTemplate.js
  src/middlewares/mfaValidate.js
  src/routes/users.js
  src/services/user.services.js
  src/validations/mfaValidation.js
  tests/login-mfa.test.js
  tests/login.test.js
  tests/users.test.js
Labels: ready for review

#40 #184581359 User change password after x-time
  .env.example
  README.md
  package-lock.json
  package.json
  src/app.js
  src/controllers/users.controllers.js
  src/database/migrations/20230308210129-create-users.js
  src/database/models/users.js
  src/docs/users.js
  src/helpers/eventEmitter.js
  src/helpers/mailTemplate.js
  src/middlewares/passwordExpiration.js
  src/routes/users.js
  tests/login-mfa.test.js
  tests/users.test.js
Labels: enhancement, ready for review

#32 #184581332 Login with google account
  .env.example
  package-lock.json
  package.json
  src/app.js
  src/database/seeders/20230309104901-users.js
  src/routes/auth.js
  tests/users.test.js
Labels: enhancement, ready for review

#42 #184581343 Seller to delete a specific item from their collection
  README.md
  src/controllers/products.controllers.js
  src/docs/product.js
  src/docs/users.js
  src/routes/products.js
  src/services/product.services.js
  tests/products.test.js
  tests/users.test.js
Labels: enhancement, ready for review

#43 #184581342 change product availability
  .env.example
  README.md
  package.json
  src/controllers/products.controllers.js
  src/docs/product.js
  src/helpers/emailConfig.js
  src/middlewares/isProductAvailable.js
  src/routes/products.js
  src/services/product.services.js
  src/services/user.services.js
  tests/products.test.js
Labels: enhancement, ready for review

#37 #184581339 Admin should be able to set roles/permissions
  README.md
  package-lock.json
  package.json
  src/configs/cloudinary.js
  src/configs/multer.js
  src/controllers/users.controllers.js
  src/docs/users.js
  src/routes/users.js
  src/services/user.services.js
  tests/users.test.js
Labels: ready for review

#45 #184581348 buyer adds product reviews
  package-lock.json
  package.json
  src/controllers/products.controllers.js
  src/controllers/reviews.contollers.js
  src/database/migrations/20230319204639-create-review.js
  src/database/models/category.js
  src/database/models/reviews.js
  src/database/seeders/20230319210520-product-seeds.js
  src/database/seeders/20230319212610-review-seed.js
  src/docs/reviews.yml
  src/helpers/mail.js
  src/middlewares/catchError.js
  src/routes/index.js
  src/routes/products.js
  src/routes/reviews.routes.js
  src/services/product.services.js
  src/services/user.services.js
  src/validations/review.validation.js
  tests/login-mfa.test.js
  tests/products.test.js
  tests/review-test.js
  tests/users.test.js
Labels: ready for review

#48 #184581358 expired product stop listing
  package-lock.json
  package.json
  src/app.js
  src/controllers/products.controllers.js
  src/database/migrations/20230308210129-create-users.js
  src/database/migrations/20230314123346-add_mfa_enabled_to_users_table.js
  src/helpers/expiredProduct.js
  src/helpers/mailTemplate.js
  src/middlewares/productExpAll.js
  src/services/product.services.js
  tests/products.test.js
Labels: enhancement, ready for review

#54 184581352 buyer can clear their cart
  src/controllers/cart.controller.js
  src/docs/cart.js
  src/routes/cart.js
  src/services/carts.services.js
  tests/cart.test.js
Labels: ready for review

#55 #184581356 buyer should be able to checkout
  .eslintrc.json
  package.json
  src/controllers/checkout.js
  src/database/migrations/20230308210129-create-users.js
  src/database/migrations/20230323110332-create-order.js
  src/database/migrations/20230323111021-create-order-item.js
  src/database/models/cart.js
  src/database/models/order.js
  src/database/models/orderitem.js
  src/database/models/products.js
  src/database/models/users.js
  src/database/seeders/20230309104901-users.js
  src/database/seeders/20230319210520-product-seeds.js
  src/database/seeders/20230323121648-order-seeds.js
  src/database/seeders/20230323121656-order-item-seeds.js
  src/docs/checkout.yml
  src/middlewares/wishlist/doesProductExist.js
  src/routes/checkout.js
  src/routes/index.js
  src/services/carts.services.js
  src/validations/checkout.validation.js
  tests/checkout.test.js
  tests/login-mfa.test.js
  tests/products.test.js
  tests/users.test.js
Labels: ready for review

#49 #184581361 Chat on the App publicly
  README.md
  package-lock.json
  package.json
  public/chat/chat.html
  public/chat/css/style.css
  public/chat/index.html
  public/chat/js/main.js
  src/app.js
  src/controllers/chat.controller.js
  src/controllers/products.controllers.js
  src/controllers/users.controllers.js
  src/database/migrations/20230322072543-create-chat.js
  src/database/migrations/20230323110332-create-order.js
  src/database/migrations/20230323111021-create-order-item.js
  src/database/models/chat.js
  src/database/models/users.js
  src/database/seeders/20230319210520-product-seeds.js
  src/docs/message.js
  src/docs/product.js
  src/helpers/chat/message.js
  src/helpers/chat/user.js
  src/helpers/socket.js
  src/routes/chat.js
  src/routes/index.js
  src/server.js
  src/services/chat.services.js
  src/services/user.services.js
  tests/chat.test.js
  tests/email.test.js
  tests/products.test.js
Labels: documentation, ready for review

#58 #184581353 User should be able to search a product
  src/controllers/products.controllers.js
  src/docs/product.js
  src/routes/products.js
  src/services/product.services.js
  tests/products.test.js
Labels: ready for review

#57 #184581330 Logout Functionality
  src/controllers/cart.controller.js
  src/controllers/users.controllers.js
  src/database/migrations/20230326185144-create-blockedtoken.js
  src/database/models/blockedtoken.js
  src/docs/users.js
  src/helpers/socket.js
  src/middlewares/verifyToken.js
  src/routes/users.js
  src/services/user.services.js
  tests/cart.test.js
  tests/products.test.js
  tests/users.test.js
  tests/wishlist.test.js
Labels: ready for review

#61 #184797812 admin should able to crud on users
  .env.example
  .eslintrc.json
  .hound.yml
  events/eventEmitter/productEvents.js
  events/eventEmitter/user.js
  events/eventHandler/eventHandler.js
  events/eventHandler/user.js
  package-lock.json
  package.json
  public/chat/js/main.js
  src/controllers/admin.controller.js
  src/controllers/notification.controller.js
  src/database/migrations/20230315082056-create-products.js
  src/database/migrations/20230318201904-wishlist-table.js
  src/database/migrations/20230319204639-create-review.js
  src/database/migrations/20230322072543-create-chat.js
  src/database/migrations/20230326193627-notifications-table.js
  src/database/models/chat.js
  src/database/models/notification.js
  src/database/models/users.js
  src/database/seeders/20230328125840-notification-seeds.js
  src/docs/admin.yml
  src/docs/notification.yml
  src/docs/reviews.yml
  src/docs/wishlist.js
  src/helpers/socket.util.js
  src/middlewares/notification.middleware.js
  src/routes/index.js
  src/routes/notification.js
  src/routes/users.js
  src/services/notification.services.js
  src/services/product.services.js
  src/services/user.services.js
  tests/admin.test.js
  tests/login-mfa.test.js
  tests/read-unread-notification.test.js
Labels: documentation, ready for review

#60 184797810 admin should be able to CRUD product
  src/middlewares/isowner.js
  src/routes/products.js
  tests/products.test.js
Labels: ready for review

#63 #184797809 Buyers should be able to CRUD the orders
  src/controllers/checkout.js
  src/docs/checkout.yml
  src/docs/orders.js
  src/routes/checkout.js
  src/routes/products.js
  tests/checkout.test.js
Labels: ready for review

#66 #184581355 payment with stripe api
  .env.example
  package-lock.json
  package.json
  public/paymentUI/cart.html
  public/paymentUI/index.html
  public/paymentUI/success.html
  src/app.js
  src/controllers/checkout.js
  src/controllers/payment.controllers.js
  src/database/migrations/20230323110332-create-order.js
  src/database/migrations/20230329063942-create-payment.js
  src/database/models/order.js
  src/database/models/payment.js
  src/database/models/products.js
  src/database/seeders/20230323121648-order-seeds.js
  src/docs/checkout.yml
  src/helpers/jwt.js
  src/helpers/mailTemplate.js
  src/routes/checkout.js
  src/routes/index.js
  src/routes/payment.js
  src/services/carts.services.js
  src/services/payment.services.js
  src/services/product.services.js
  tests/login-mfa.test.js
  tests/payment.test.js
Labels: enhancement, ready for review

#72 184797811 admin get all orders from all buyers
  src/controllers/checkout.js
  src/docs/orders.js
  src/routes/checkout.js
  tests/checkout.test.js
Labels: ready for review
